---
services:
  db:
    image: postgres
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: example
    ports: [5432:5432]
  scraper:
    build:
      context: .
      dockerfile: koyomi-scraper/Dockerfile
    env_file: .env
  api:
    build:
      context: .
      dockerfile: koyomi-api/Dockerfile
    env_file: .env
    ports: [3000:3000]
